import {
  LayoutDashboard,
  Building2,
  BedDouble,
  ClipboardList,
  UtensilsCrossed,
  Users,
  TrendingUp,
  TrendingDown,
  MessageSquareText,
  Star,
  CalendarClock,
  ChefHat,
  Hotel,
  AlertTriangle,
  AlertCircle,
  Sparkles,
  X,
  Check,
  ChevronDown,
  Loader2,
  DollarSign,
  ClipboardCheck,
  Utensils,
  Send,
  MessageCircleWarning,
  UserX,
  Radio,
  LogIn,
  LogOut,
  SprayCan,
  Wrench,
  ContactRound,
  Heart,
  BarChart3,
  LineChart,
  Bot,
  ShieldCheck,
  Settings,
  Layers,
  ChevronRight,
  Search,
  Filter,
  Table2,
  Calendar,
  LayoutGrid,
  Cloud,
  PartyPopper,
  Gauge,
  Trash2,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutDashboard,
  hotel: Building2,
  bed: BedDouble,
  bookings: ClipboardList,
  restaurant: UtensilsCrossed,
  staff: Users,
  pricing: TrendingUp,
  trendDown: TrendingDown,
  assistant: MessageSquareText,
  guestExperience: Star,
  staffing: CalendarClock,
  demandForecast: ChefHat,
  brand: Hotel,
  alert: AlertTriangle,
  alertCircle: AlertCircle,
  insight: Sparkles,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  spinner: Loader2,
  revenue: DollarSign,
  reservations: ClipboardCheck,
  restaurantSales: Utensils,
  send: Send,
  complaint: MessageCircleWarning,
  churnRisk: UserX,
  live: Radio,
  checkIn: LogIn,
  checkOut: LogOut,
  housekeeping: SprayCan,
  maintenance: Wrench,
  loyalty: Heart,
  guests: ContactRound,
  reports: BarChart3,
  analytics: LineChart,
  ai: Bot,
  admin: ShieldCheck,
  settings: Settings,
  portfolio: Layers,
  chevronRight: ChevronRight,
  search: Search,
  filter: Filter,
  table: Table2,
  calendar: Calendar,
  grid: LayoutGrid,
  weather: Cloud,
  events: PartyPopper,
  utilization: Gauge,
  foodWaste: Trash2,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface IconProps {
  name: IconName;
  className?: string;
  size?: number;
}

export function Icon({ name, className, size = 18 }: IconProps) {
  const Component = ICONS[name];
  return <Component className={className} size={size} aria-hidden="true" />;
}
